import { appendFileSync, readFileSync } from 'node:fs';
import { ContractFactory, JsonRpcProvider, Wallet, formatEther } from 'ethers';
import { BNB_CHAIN } from '../src/bnb-chain.js';
import { loadBnbConfig } from '../src/bnb-config.js';
import { assessWalletStop, loadBnbBaseline, readBnbValuation, usd8FromBnbWei } from '../src/bnb-risk.js';

const config = loadBnbConfig();
const execute = process.argv[2] === '--execute';
if (process.argv[2] && !execute) throw new Error('Usage: npm run deploy-bnb -- [--execute]');
if (!config.executorKey) throw new Error('Import the BNB wallet locally first');
if (config.contractAddress) throw new Error('BNB executor already configured; refusing to redeploy');
const provider = new JsonRpcProvider(config.rpcUrl);
if ((await provider.getNetwork()).chainId !== BNB_CHAIN.chainId) throw new Error('Expected BNB Smart Chain');
const wallet = new Wallet(config.executorKey, provider);
if (wallet.address.toLowerCase() !== config.expectedAddress.toLowerCase()) throw new Error('Private key does not match selected BNB wallet');
const artifact = JSON.parse(readFileSync('artifacts/AtomicVerifiedMixedArb.json', 'utf8'));
const args = [BNB_CHAIN.wbnb, BNB_CHAIN.v2Factory, BNB_CHAIN.v3Factory, BNB_CHAIN.v3Router];
const factory = new ContractFactory(artifact.abi, artifact.bytecode, wallet);
const estimate = await provider.estimateGas({ ...(await factory.getDeployTransaction(...args)), from: wallet.address });
const gasLimit = estimate * 12n / 10n;
const gasPrice = (await provider.getFeeData()).gasPrice;
if (!gasPrice || gasPrice > config.maxGasPriceWei) throw new Error('BNB gas price exceeds configured cap');
const maxCost = gasLimit * gasPrice;
if ((await provider.getBalance(wallet.address)) < maxCost + config.nativeReserveWei) throw new Error('BNB balance would fall below the gas reserve');
const baseline = loadBnbBaseline(config.expectedAddress);
if (!baseline) throw new Error('Set the fixed BNB wallet USD baseline before deployment');
const value = await readBnbValuation(provider, config.expectedAddress);
const risk = assessWalletStop({ baselineUsd8: BigInt(baseline.valueUsd8), currentUsd8: value.valueUsd8, limitUsd8: config.maxWalletLossUsd8, pendingGasUsd8: usd8FromBnbWei(maxCost, value.priceUsd8) });
if (!risk.maySend) throw new Error('Deployment could exceed the $15 wallet loss budget');
console.log(`${execute ? 'Deploying' : 'Previewing'} BNB executor: estimated gas ${estimate}, maximum cost ${formatEther(maxCost)} BNB at current gas price`);
if (!execute) process.exit(0);
const contract = await factory.deploy(...args, { gasLimit, gasPrice });
console.log(`Deployment transaction: ${contract.deploymentTransaction().hash}`);
await contract.waitForDeployment();
const address = await contract.getAddress();
appendFileSync('.env.bnb.local', `\nBNB_ARB_CONTRACT_ADDRESS=${address}\n`);
console.log(`BNB_ARB_CONTRACT_ADDRESS=${address}`);
